run:
  timeout: 5m
  tests: true
  # Using exclude-dirs instead of deprecated skip-dirs
  # skip-dirs:
  #   - test-projet

issues:
  exclude-dirs:
    - test-projet
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck

linters:
  disable-all: true
  enable:
    # Removing deprecated linters
    # - deadcode
    # - structcheck 
    # - varcheck
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gofmt

linters-settings:
  goimports:
    local-prefixes: turbotilt
