run:
  timeout: 5m
  tests: true
  skip-dirs:
    - test-projet

linters:
  disable-all: true
  enable:
    - deadcode
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - structcheck
    - typecheck
    - unused
    - varcheck
    - gofmt
    - goimports
    - misspell

linters-settings:
  goimports:
    local-prefixes: turbotilt

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
