micronaut:
  application:
    name: payment-service
  server:
    port: 8083

datasources:
  default:
    url: jdbc:postgresql://postgres:5432/paymentdb
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true

logger:
  levels:
    io.micronaut: INFO
    com.example.paymentservice: DEBUG
